# Generated by Django 6.0.4 on 2026-05-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha',
            field=models.DateField(),
        ),
    ]
