# Generated by Django 6.0.4 on 2026-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_expediente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='hora',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
