# Generated by Django 6.0.4 on 2026-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_expediente_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='codigo_cie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expediente',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expediente',
            name='nota_adicional',
            field=models.TextField(blank=True),
        ),
    ]
