# Generated by Django 6.0.4 on 2026-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_expediente_codigo_cie_expediente_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre_es', models.TextField()),
                ('nombre_en', models.TextField()),
            ],
        ),
    ]
